---
#
# Generic Playbook to install collectd on generic machine types, use tags to seperate machine type:
#
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="graphite"
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="satellite6"
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="capsules"
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="docker-hosts"
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="satellite6,capsules"
- hosts: satellite6
  vars:
    config_type: satellite6
  vars_files:
    - ../conf/satmon.yaml
  roles:
    - collectd-generic
  tags: satellite6

- hosts: capsules
  vars:
    config_type: capsules
  vars_files:
    - ../conf/satmon.yaml
  roles:
    - collectd-generic
  tags: capsules
